### ISSUE TITLE
Docker部署Nacos

### ISSUE THREAD

**Issue by Junior233** [Junior233/blog_articles#126]
文档
https://nacos.io/zh-cn/docs/quick-start-docker.html

克隆项目
``` shell
git clone https://github.com/nacos-group/nacos-docker.git
cd nacos-docker
```

Nacos控制台和MySQL默认账号密码
nacos/nacos

mysql8单机模式

```yml
version: "2"
services:
  nacos:
    image: nacos/nacos-server:${NACOS_VERSION}
    container_name: nacos-standalone-mysql
    env_file:
      - ../env/nacos-standlone-mysql.env
    volumes:
      - ./standalone-logs/:/home/nacos/logs
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9555:9555"
    depends_on:
      - mysql
    restart: always
  mysql:
    container_name: mysql
    image: nacos/nacos-mysql:8.0.16
    env_file:
      - ../env/mysql.env
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3310:3306"
    restart: always
```

`docker compose -f  standalone-mysql-8.yaml up -d`

![image](https://user-images.githubusercontent.com/67447332/179487553-af49f4cd-efd3-4d59-8701-e483fae1115a.png)

进入nacos容器内部测试能否通过mysql的容器名跟mysql容器通信
`docker exec -it <容器> /bin/bash`
![image](https://user-images.githubusercontent.com/67447332/184886430-fc9d0842-f169-47c9-9f68-25baccc3a190.png)

安装prometheus
``` shell
docker run \
    -p 9090:9090 \
    -v /root/nacos-docker/example/prometheus/prometheus-standalone.yaml:/etc/prometheus/prometheus.yml \
	-d --restart=always --net host \
    prom/prometheus
```

![image](https://user-images.githubusercontent.com/67447332/179487448-63461df5-f1f9-4470-9894-05292bc177ac.png)

安装grafana  // 默认密码 admin/admin
``` shell
docker run -d --name=grafana --restart=always  -p 3000:3000 grafana/grafana-enterprise:9.0.2-ubuntu
```
![image](https://user-images.githubusercontent.com/67447332/179487040-2c3eef5a-8a95-4caa-bcda-48e41ee08e82.png)

![image](https://user-images.githubusercontent.com/67447332/179487315-23bf1df5-ee3b-48f0-8992-cbfa5a06039a.png)

https://prometheus.io/docs/prometheus/latest/installation/#using-docker
https://grafana.com/docs/grafana/latest/setup-grafana/installation/docker/
