### ISSUE TITLE
Kubernetes安装mongodb

### ISSUE THREAD

**Issue by Junior233** [Junior233/blog_articles#131]
Kubernetes安装mongodb

```yaml
---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: example-mongodb
spec:
  members: 1
  type: ReplicaSet
  version: "4.2.6"
  statefulSet:
    spec:
      template:
        spec:
          #  Hostpath volumes are owned by root
          #  but MongoDB containers run as non root
          #  so we use an init container to change the owner of
          #  the directory (init containers run as root)
          initContainers:
          - command:
              - chown
              - -R
              - "2000"
              - /data
            image: busybox
            volumeMounts:
            - mountPath: /data
              name: data-volume
            securityContext:
              runAsNonRoot: false
              runAsUser: 0
              runAsGroup: 0
            name: change-dir-permissions
      volumeClaimTemplates:
      - metadata:
          name: data-volume
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 8G
          selector:
            matchLabels:
              # We set this labels when creating the volume
              # (see below)
              type: data
          storageClassName: default
      - metadata:
          name: logs-volume
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 8G
          selector:
            matchLabels:
              type: logs
          storageClassName: default
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: root
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: my-user-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
        - name: root
          db: admin  
      scramCredentialsSecretName: my-scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
  
# the user credentials will be generated from this secret
# once the credentials are generated, this secret is no longer required
---
apiVersion: v1
kind: Secret
metadata:
  name: my-user-password
type: Opaque
stringData:
  password: <密码>

---
# Here we create 6 PVs: two for each ReplicaSet member
# (one for data, one for logs)
apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    labels:
      type: data
    name: data-volume-0
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 8G
    hostPath:
      path: /opt/data/mongo-data-0
      type: ""
    persistentVolumeReclaimPolicy: Delete
    storageClassName: default
    volumeMode: Filesystem
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    labels:
      type: logs
    name: logs-volume-0
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 8G
    hostPath:
      path: /opt/data/mongo-logs-0
      type: ""
    persistentVolumeReclaimPolicy: Delete
    storageClassName: default
    volumeMode: Filesystem
kind: List
---  


---
kind: Service
apiVersion: v1
metadata:
  name: external-mongo-service-0
  annotations:
    kube-linter.io/ignore-all: "used for sample"
spec:
  type: NodePort
  selector:
    app: example-mongodb-svc
    statefulset.kubernetes.io/pod-name: example-mongodb-0
  ports:
    - protocol: TCP
      nodePort: 27017
      port: 31181
      targetPort: 27017


---
```

https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/docs/install-upgrade.md

https://github.com/mongodb/mongodb-kubernetes-operator/tree/master/config/samples
